{% set version = "4.2.8.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-openxlsx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/openxlsx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/openxlsx/openxlsx_{{ version }}.tar.gz
  sha256: 46ed7c1c8db9646eaf4fe6abe00a0eacd40d28707428a7c611c2816195c71a63

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-stringi                  # [build_platform != target_platform]
    - r-zip                      # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-stringi
    - r-zip
  run:
    - r-base
    - r-rcpp
    - r-stringi
    - r-zip

test:
  commands:
    - $R -e "library('openxlsx')"           # [not win]
    - "\"%R%\" -e \"library('openxlsx')\""  # [win]

about:
  home: https://ycphs.github.io/openxlsx/index.html, https://github.com/ycphs/openxlsx
  license: MIT
  summary: Simplifies the creation of Excel .xlsx files by providing a high level interface to writing, styling and editing worksheets. Through the use of 'Rcpp', read/write times are comparable to the 'xlsx' and 'XLConnect' packages with the added benefit of removing the dependency on Java.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
